spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lichking2018/config-repo
          username: lichking2018@aliyun.com
          password: xuehu1104
          basedir: /Users/lichking2015/Documents/workspace/config/basedir
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"

